<form class="form-horizontal" action="login" method="post">
  <div class="control-group">
    <label class="control-label" for="inputEmail">Usuario:</label>
    <div class="controls">
      <input type="text" name="usuario" id="inputEmail" placeholder="Usuario">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Contraseña:</label>
    <div class="controls">
      <input type="password" name="clave" id="inputPassword" placeholder="Contraseña">
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">Ingresar</button>
    </div>
  </div>
</form>
<?=$this->messages?>