<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-striped table-bordered" >
        <thead>
            <tr><th>Id</th><th>Nombre</th><th>Descripción</th><th>Estado</th><th>Registro</th><th>Opciones</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            $estado = 'checkmark.png';
            echo '<tr>';
            echo '<td>'.$value['id'].'</td>';
            echo '<td>'.$value['nombre'].'</td>';
            echo '<td>'.$value['descripcion'].'</td>';
            if ($value['estado'] == Admin_MvcController::INACTIVO)
                $estado = 'error.png';
            echo '<td width=8%><span style=display:none>'.$value['estado'].'</span><img src='.SITE_URL.'/img/'.$estado.' width=20%></td>';
            echo '<td>'.$value['fecha_crea'].'</td>';
            echo '<td width=15%><a  href="#myModal" role="button" class="btn btn-mini" data-toggle="modal" onclick="editar('.$value['id'].')">Editar</a>
                    <a  href="#" role="button" class="btn btn-mini" onclick="elimina('.$value['id'].')">Eliminar</a></td>';
            echo '</tr>';
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>
