<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered" >
        <thead>
            <tr><th></th><th>Id</th><th>Nombres</th><th>Celular</th><th>Correo</th><th>Mensaje</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            $estado = 'checkmark.png';
            echo '<tr>';
            echo '<td width = 8%>';
            echo '<div class="btn-group dropup">
		  <button class="btn btn-mini btn-inverse">Opciones</button>
		  <button class="btn btn-mini btn-inverse dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
		  <ul class="dropdown-menu">
                    <li><a href="#myModal" data-toggle="modal" onclick="editar('.$value['id'].')"><i class="icon-pencil"></i> Editar</a></li>
                    <li><a href="#myModal" data-toggle="modal" onclick="elimina('.$value['id'].')"><i class="icon-trash"></i> Eliminar</a></li>
		  </ul>
		</div>';
            echo '</td>';
            echo '<td>'.$value['id'].'</td>';
            echo '<td>'.$value['nombres'].'</td>';
            echo '<td>'.$value['celular'].'</td>';
            echo '<td>'.$value['correo'].'</td>';
            echo '<td>'.$value['mensaje'].'</td>';
            echo '</tr>';
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>
