<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered">
        <thead>
            <tr>
                <th></th><th>Id pedido</th><th>Cliente</th><th>Entregado</th><th>Fecha pedido</th><th>Fecha entrega</th>
            </tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            echo '<tr>';
            echo '<td width=5% class="taskOptions">';
            echo '<a data-original-title="Editar" class="tip-top" href="#myModal" data-toggle="modal" onclick="editar('.$value['id'].')">';
            echo '<i class="icon-pencil"></i></a>&nbsp;&nbsp;';
            echo '<a data-original-title="Eliminar" class="tip-top" href="#myModal" data-toggle="modal" onclick="elimina('.$value['id'].')">';
            echo '<i class="icon-trash"></i></a>';
            echo '</td>';
            echo '<td>'.$value['id'].'</td>';
            echo '<td>'.$value['nombres'].'</td>';
            echo '<td>'.$value['entregado'].'</td>';
            echo '<td>'.$value['fecha_genera'].'</td>';
            echo '<td>'.$value['fecha_entrega'].'</td>';
            echo '</tr>';
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>