<a href="#myModal" role="button" class="btn" id='btnNuevo' data-toggle="modal">Nuevo</a>
<table id='tabla' class="table table-striped table-bordered">
    <thead>
        <tr><th>Id</th><th>Nombre</th><th>Apellido</th><th>E-mail</th><th>Rol</th><th>Registro</th></tr>
    </thead>
    <?php
    echo '<tbody>';
    foreach ($this->data as $value) {
        echo '<tr>';
        echo '<td>'.$value['id'].'</td>';
        echo '<td>'.$value['nombres'].'</td>';
        echo '<td>'.$value['apellidos'].'</td>';
        echo '<td>'.$value['email'].'</td>';
        echo '<td>'.$value['id_rol'].'</td>';
        echo '<td>'.$value['fecha_registro'].'</td>';
        echo '</tr>';
    }
    echo '</tbody>';
    ?>
</table>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>