<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered">
        <thead>
            <tr><th>Id</th><th>Nombre</th><th>Apellido</th><th>E-mail</th><th>Rol</th>
                <th>Teléfono</th><th>Celular</th><th>Dirección</th><th>Fecha nac.</th><th>Opciones</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            echo '<tr>';
            echo '<td>'.$value['id'].'</td>';
            echo '<td>'.$value['nombres'].'</td>';
            echo '<td>'.$value['apellidos'].'</td>';
            echo '<td>'.$value['email'].'</td>';
            echo '<td>'.$value['id_rol'].'</td>';
            echo '<td>'.$value['telefono'].'</td>';
            echo '<td>'.$value['celular'].'</td>';
            echo '<td>'.$value['direccion'].'</td>';
            echo '<td>'.$value['fecha_nac'].'</td>';
            echo '<td><a  href="#myModal" role="button" class="btn btn-mini" data-toggle="modal" onclick="editar('.$value['id'].')">Editar</a>
                    <a  href="#myModal" role="button" class="btn btn-mini" data-toggle="modal" onclick="elimina('.$value['id'].')">Eliminar</a></td>';
            echo '</tr>';
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>