<style>
    dt,  dd{ float:left; }
     dt{ width:200px; }
</style>
<a href="#myModal" role="button" class="btn" id='btnNuevo' data-toggle="modal">Nueva categoría</a>
<table id='tablaCategoria' class="table table-striped table-bordered">
    <thead>
        <tr><th>Id</th><th>Descripción</th><th>Estado</th><th>Registro</th><th>Opciones</th></tr>
    </thead>
    <?php
    echo '<tbody>';
    foreach ($this->categoria as $value) {
        $estado = 'checkmark.png';
        echo '<tr>';
        echo '<td>'.$value['id'].'</td>';
        echo '<td>'.$value['nom_cat'].'</td>';
        if ($value['estado'] == Application_Model_Categoria::INACTIVA)
            $estado = 'error.png';
        echo '<td width=8%><span style=display:none>'.$value['estado'].'</span><img src='.SITE_URL.'/jquery/css/images/'.$estado.' width=20%></td>';
        echo '<td>'.$value['fecha_crea'].'</td>';
        echo '<td><a  href="#myModal" role="button" class="btn" data-toggle="modal" onclick="editarCategoria('.$value['id'].')">Editar</a></td>';
        echo '</tr>';
    }
    echo '</tbody>';
    ?>
</table>

<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="modalTitle">Nueva categoría</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" id="btnClose" aria-hidden="true">Cerrar</button>
    <button class="btn btn-primary" id="btnGuardar">Grabar</button>
  </div>
</div>



