<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?=TITLE?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href=<?=SITE_URL.'/assets/css/bootstrap.css'?> rel="stylesheet">
    <link href=<?=SITE_URL.'/assets/css/bootstrap-responsive.css'?> rel="stylesheet">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href=<?=SITE_URL.'/assets/ico/favicon.ico'?>>
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href=<?=SITE_URL.'/assets/ico/apple-touch-icon-144-precomposed.png'?>>
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href=<?=SITE_URL.'/assets/ico/apple-touch-icon-114-precomposed.png'?>>
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href=<?=SITE_URL.'/assets/ico/apple-touch-icon-72-precomposed.png'?>>
    <link rel="apple-touch-icon-precomposed" href=<?=SITE_URL.'/assets/ico/apple-touch-icon-57-precomposed.png'?>>
    <?=$this->headLink() ?>
    <script src=<?=SITE_URL.'/assets/js/jquery.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-transition.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-alert.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-modal.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-dropdown.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-scrollspy.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-tab.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-tooltip.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-popover.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-button.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-collapse.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-carousel.js'?>></script>
    <script src=<?=SITE_URL.'/assets/js/bootstrap-typeahead.js'?>></script>
    <script src=<?=SITE_URL.'/jquery/plugins/jquery.default.js'?>></script>
    <?=$this->headScript() ?>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="<?=SITE_URL?>"><?=TITLE?></a>
          <div class="nav-collapse collapse">
            <ul class="nav" role="navigation">
                    <li class="dropdown">
                      <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Mantenimiento <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <li class="<?=($this->layout()->active == 'usuarios')?'':''?>"><a href="<?=SITE_URL.'/admin/usuario'?>">Usuarios</a></li>
                        <li class="<?=($this->layout()->active == 'productos')?'':''?>"><a href="<?=SITE_URL.'/admin/producto'?>">Producto</a></li>
                        <li class="<?=($this->layout()->active == 'categorias')?'':''?>"><a href="<?=SITE_URL.'/admin/categoria'?>">Categoría</a></li>
                      </ul>
                    </li>
            </ul>
            <ul class="nav pull-right">
                    <li id="fat-menu" class="dropdown">
                        <a href="" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">Usuario: Martin Grados<b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <li><a tabindex="-1" href="<?=SITE_URL.'/logout'?>">Cerrar sesión</a></li>
                      </ul>
                    </li>
            </ul>
              
          </div>
        </div>
      </div>
    </div>
      <div class='container'><?=$this->layout()->content?></div>
  </body>
</html>

