<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Unicorn Admin</title>
		<meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href=<?=SITE_URL."/css/bootstrap.min.css"?> />
		<link rel="stylesheet" href=<?=SITE_URL."/css/bootstrap-responsive.min.css"?> />
		<link rel="stylesheet" href=<?=SITE_URL."/css/uniform.css"?> />
		<link rel="stylesheet" href=<?=SITE_URL."/css/chosen.css"?> />
                <link rel="stylesheet" href=<?=SITE_URL."/css/unicorn.main.css"?> />
		<link rel="stylesheet" href=<?=SITE_URL."/css/unicorn.grey.css"?> class="skin-color" />
					
                
                <script src=<?=SITE_URL."/js/excanvas.min.js"?> ></script>
                <script src=<?=SITE_URL."/js/jquery.min.js"?> ></script>
                <script src=<?=SITE_URL."/js/jquery.ui.custom.js"?> ></script>
                <script src=<?=SITE_URL."/js/bootstrap.min.js"?> ></script>
                <script src=<?=SITE_URL."/js/jquery.flot.min.js"?> ></script>
                <script src=<?=SITE_URL."/js/jquery.flot.resize.min.js"?> ></script>
                <script src=<?=SITE_URL."/js/jquery.peity.min.js"?> ></script>
                <script src=<?=SITE_URL."/js/fullcalendar.min.js"?> ></script>
                <script src=<?=SITE_URL."/js/unicorn.js"?> ></script>

  
                <script src=<?=SITE_URL."/js/jquery.uniform.js"?> ></script>
                <script src=<?=SITE_URL."/js/jquery.chosen.js"?> ></script>
                <script src=<?=SITE_URL."/js/jquery.dataTables.min.js"?> ></script>
                <script src=<?=SITE_URL."/js/unicorn.tables.js"?> ></script>
                
                <script src=<?=SITE_URL."/js/web/validate.js"?> ></script>
                <script src=<?=SITE_URL."/js/web/mvc.js"?> ></script>

                <?=$this->headScript() ?>
	</head>
	<body>
		
		
		<div id="header">
			<h1><a href="./dashboard.html">Unicorn Admin</a></h1>		
		</div>
		
		<div id="search">
			<input type="text" placeholder="Search here..."/><button type="submit" class="tip-right" title="Search"><i class="icon-search icon-white"></i></button>
		</div>
		<div id="user-nav" class="navbar">
            <ul class="nav btn-group">
                <li class="btn btn-inverse" ><a title="" href="#"><i class="icon icon-user"></i> <span class="text">Profile</span></a></li>
                <li class="btn btn-inverse dropdown" id="menu-messages"><a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a class="sAdd" title="" href="#">new message</a></li>
                        <li><a class="sInbox" title="" href="#">inbox</a></li>
                        <li><a class="sOutbox" title="" href="#">outbox</a></li>
                        <li><a class="sTrash" title="" href="#">trash</a></li>
                    </ul>
                </li>
                <li class="btn btn-mini btn-inverse"><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
                <li class="btn btn-mini btn-inverse"><a title="" href=<?=SITE_URL.'/logout'?> ><i class="icon icon-share-alt"></i> <span class="text">Salir</span></a></li>
            </ul>
        </div>
            
		<div id="sidebar">
			<a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
			<ul>
                            <!-- Sería un menú dinámico -->
				<li class="submenu open">
					<a href="#"><i class="icon icon-th-list"></i> <span>Mantenimiento</span> <span class="label">5</span></a>
					<ul>
                                                <li class="<?=($this->layout()->active == 'Usuarios')?'active':''?>"><a href="<?=SITE_URL.'/admin/mvc/usuario'?>">Usuarios</a></li>
						<li class="<?=($this->layout()->active == 'Productos')?'active':''?>"><a href="<?=SITE_URL.'/admin/mvc/producto'?>">Producto</a></li>
                                                <li class="<?=($this->layout()->active == 'Categorias')?'active':''?>"><a href="<?=SITE_URL.'/admin/mvc/categoria'?>">Categoría</a></li>
                                                <li class="<?=($this->layout()->active == 'Rols')?'active':''?>"><a href="<?=SITE_URL.'/admin/mvc/rol'?>">Rol</a></li>
                                                <li class="<?=($this->layout()->active == 'Recursos')?'active':''?>"><a href="<?=SITE_URL.'/admin/mvc/recurso'?>">Recurso</a></li>
					</ul>
				</li>
                                <li><a href="tables.html"><i class="icon icon-th"></i> <span>Configuración</span></a></li>
                                <li class="submenu">
					<a href="#"><i class="icon icon-th-list"></i> <span>Proceso</span> <span class="label">2</span></a>
					<ul>
						<li><a href="invoice.html">Pedidos</a></li>
						<li><a href="chat.html">Contáctenos</a></li>
					</ul>
				</li>
			</ul>
		</div>
		
		<div id="style-switcher">
			<i class="icon-arrow-left icon-white"></i>
			<span>Style:</span>
			<a href="#grey" style="background-color: #555555;border-color: #aaaaaa;"></a>
			<a href="#blue" style="background-color: #2D2F57;"></a>
			<a href="#red" style="background-color: #673232;"></a>
		</div>
		
		<div id="content">
			<div id="content-header">
				<h1><?=$this->layout()->active?>&nbsp;
                                    <a href="#myModal" role="button" class="btn" id='btnNuevo' data-toggle="modal">Nuevo</a>
                                </h1>
                                
				<div class="btn-group">
					<a class="btn btn-large tip-bottom" title="Manage Files"><i class="icon-file"></i></a>
					<a class="btn btn-large tip-bottom" title="Manage Users"><i class="icon-user"></i></a>
					<a class="btn btn-large tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a>
					<a class="btn btn-large tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a>
				</div>
			</div>
			<div id="breadcrumb">
				<a href="#" title="Ir al inicio" class="tip-bottom"><i class="icon-home"></i> Inicio</a>
				<a href="#" class="current"><?=$this->layout()->active?></a>
			</div>
			<div class="container-fluid">
                                                                        
                            <?php echo $this->layout()->content;?>
				<?=$this->partial('pie.phtml');?>
			</div>
		</div>
		
	</body>
</html>
