<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Admin</title>
		<meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="css/bootstrap.min.css" />
		<link rel="stylesheet" href="css/bootstrap-responsive.min.css" />
        <link rel="stylesheet" href="css/unicorn.login.css" />
    </head>
    <body>
        <div id="logo">
            <img src="img/logo.png" alt="" />
        </div>
        <div id="loginbox">            
            <form id="loginform" class="form-vertical" action="login" method="post">
				<p>Ingresa tu correo y contraseña</p>
                <div class="control-group">
                    <div class="controls">
                        <div class="input-prepend">
                            <span class="add-on"><i class="icon-user"></i></span><input type="text" name="usuario" placeholder="Correo" />
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="input-prepend">
                            <span class="add-on"><i class="icon-lock"></i></span><input type="password" name="clave" placeholder="Contraseña" />
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <span class="pull-left"><a href="#" class="flip-link" id="fliptorecover">¿Olvidaste tu contraseña?</a></span>
                    <span class="pull-right"><input type="submit" class="btn btn-inverse" value="Login" /></span>
                </div>
            </form>
            <form id="recoverform" action="#" class="form-vertical">
				<p>Ingrese su correo y le enviaremos las instrucciones para recuperar su contraseña</p>
				<div class="control-group">
                    <div class="controls">
                        <div class="input-prepend">
                            <span class="add-on"><i class="icon-envelope"></i></span><input type="text" placeholder="Correo" />
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <span class="pull-left"><a href="#" class="flip-link" id="fliptologin">&lt; Volver al login</a></span>
                    <span class="pull-right"><input type="submit" class="btn btn-inverse" value="Recuperar" /></span>
                </div>
            </form>
            <?=$this->messages?>
        </div>
        
        <script src="js/jquery.min.js"></script>  
        <script>
			$(function(){

				// Checking for CSS 3D transformation support
				$.support.css3d = supportsCSS3D();

				var formContainer = $('#loginbox');

				// Listening for clicks on the ribbon links
				$('.flip-link').click(function(e){

					// Flipping the forms
					formContainer.toggleClass('flipped');

					// If there is no CSS3 3D support, simply
					// hide the login form (exposing the recover one)
					if(!$.support.css3d){
						$('#loginform').toggle();
					}
					e.preventDefault();
				});

				// A helper function that checks for the
				// support of the 3D CSS3 transformations.
				function supportsCSS3D() {
					var props = [
						'perspectiveProperty', 'WebkitPerspective', 'MozPerspective'
					], testDom = document.createElement('a');

					for(var i=0; i<props.length; i++){
						if(props[i] in testDom.style){
							return true;
						}
					}

					return false;
				}
			});      
        </script>  
    </body>
</html>
